import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";
import ItemsDescription from "~/components/itemsdescription";
import Navbar from "~/components/navbar";
import { type TeaType, milkTeaData } from "~/utils/milkTeaData";

export type ParsedItemType = TeaType & { quantity: number };

export default function Items() {
  const router = useRouter();
  const itemId = router.query.id as string;
  const item = milkTeaData
    .map((item) => item.teas)
    .flat()
    .find((item) => item.id === parseInt(itemId));

  if (!item) return <p>Item not found</p>;

  return (
    <>
      <Head>
        <title>Hi Tea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <Navbar />
        <div className="flex h-[calc(100vh-80px)] flex-col border md:h-[calc(100vh-96px)] md:flex-row">
          <figure className="relative h-[25vh] w-full md:h-[50vh] md:w-1/2">
            <Image
              src={`/hiteadrinks/${item.image}`}
              alt={"photo of " + item.name}
              fill
              className="object-contain"
            />
          </figure>
          <ItemsDescription {...item} />
        </div>
      </main>
    </>
  );
}
