import { signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import MenuItems from "~/components/menuItems";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Hi Tea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        {/* <button onClick={() => void signIn("auth0")}>Sign in</button>
        <Link href="/admin">Go To Admin</Link> */}
        <MenuItems />
      </main>
    </>
  );
}
