import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import IconButton from "~/components/iconbutton";
import Navbar from "~/components/navbar";
import { useConsole } from "~/hooks/useConsole";
import { useLocalStorage } from "~/hooks/useLocalStorage";
import { type TeaType, type TeasType } from "~/utils/milkTeaData";

export default function Checkout() {
  const [items, setItems, itemsLoading] = useLocalStorage<TeasType>(
    [],
    "items"
  );

  const router = useRouter();

  if (itemsLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Hi Tea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center">
        <Navbar />
        <div className="flex w-4/5 flex-col items-center md:w-1/2">
          <div className="flex w-full justify-between">
            <h2 className="text-xl">Order Summary</h2>
            <Link className="rounded-full border border-black p-2" href={"/"}>
              + Add items
            </Link>
          </div>
          <div className="flex flex-col gap-2">
            {items.map((item) => (
              <ItemSummary key={item.id} {...item} />
            ))}
          </div>
          <button
            className="rounded-full border border-black p-2"
            onClick={() => alert("checking out...")}
          >
            Checkout
          </button>
        </div>
      </main>
    </>
  );
}

const ItemSummary: React.FC<TeaType> = ({ id, name, image }) => {
  return (
    <div className="flex items-center">
      <Image src={`/hiteadrinks/${image}`} alt={name} width={96} height={96} />
      <p>{name}</p>
    </div>
  );
};
