import Head from "next/head";

export default function Checkout() {
  return (
    <>
      <Head>
        <title>Hi Tea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center md:flex-row">
        <h2>Checkout</h2>
      </main>
    </>
  );
}
