import Head from "next/head";
import Navbar from "./navbar";

type PageWrapperType = {
  children: React.ReactNode;
};

const PageWrapper: React.FC<PageWrapperType> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hi Tea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="relative flex h-[calc(100vh-80px)] flex-col items-center md:h-[calc(100vh-96px)]">
        {children}
      </main>
    </>
  );
};

export default PageWrapper;
